version: "3"
services:
  python:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: python main.py
    environment:
      ENV: "dev"
      LINE_CHANNEL_SECRET: "${LINE_CHANNEL_SECRET}"
      LINE_CHANNEL_ACCESS_TOKEN: "${LINE_CHANNEL_ACCESS_TOKEN}"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARE_TUNNEL_TOKEN}"
    depends_on:
      - python
